In [1]:
import numpy as np

In [2]:
lista=[1,2]
lista *2

[1, 2, 1, 2]

In [3]:
arr=np.arange(0,10)
arr2=arr.copy()

Operaciones

In [4]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1/arr

<ipython-input-8-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr + arr2
arr* arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

# Cargando archivos

In [3]:
import pandas as pd

In [4]:
df1=pd.read_csv("bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv")

In [13]:
df1[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [14]:
df1[["Name","Author"]]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

LOC: Me permite filtrar el df


In [16]:
df1.loc[0:4,["Name","Author"]]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [19]:
#Asi mismo puedo hacer un filtrado mas específico asi:
df1.loc[:,["Author"]]=="JJ Smith"

Author
0      True
1      True
2      True
3      True
4      True
..      ...
545    True
546    True
547    True
548    True
549    True

[550 rows x 1 columns]

Iloc: Búsqueda por índices

In [5]:
df1.iloc[1:3]*-1


Name Author  User Rating  Reviews  Price  Year Genre
1                     -4.6    -2052    -22 -2011      
2                     -4.7   -18979    -15 -2018

In [5]:
df2=pd.read_json("HPCharactersDataRaw.json")

In [6]:
#Puedo obtener diferente información por parte del dataframe
df1.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

Series Y dataframes


In [7]:
family=pd.Series(["Simon","Salo","Wilson","Angela","Manu"],
                 index=[1,3,5,7,9])

In [ ]:
#Tambien se puede declarar dandole un diccionario como parámetro
pd.Series(diccionario)

1     Simon
3      Salo
5    Wilson
7    Angela
9      Manu
dtype: object