In [ ]:
import numpy as np

In [ ]:
lista=[1,2]
lista *2

[1, 2, 1, 2]

In [ ]:
arr=np.arange(0,10)
arr2=arr.copy()

Operaciones

In [ ]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1/arr

<ipython-input-8-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr + arr2
arr* arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

# Cargando archivos

In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv("/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv")

In [ ]:
df2=pd.read_json("/content/HPCharactersDataRaw.json")

In [ ]:
#Puedo obtener diferente información por parte del dataframe
df1.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

Series Y dataframes


In [ ]:
family=pd.Series(["Simon","Salo","Wilson","Angela","Manu"],
                 index=[1,3,5,7,9])

In [ ]:
#Tambien se puede declarar dandole un diccionario como parámetro
pd.Series(diccionario)

1     Simon
3      Salo
5    Wilson
7    Angela
9      Manu
dtype: object